services:
  # The "Web Server"
  reverse-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      # Map your custom config
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Map your website files so Nginx can find index.html
      - ./public:/usr/share/nginx/html:ro
    restart: always

  # If you have an app that serves traffic, keep it here.
  # If you just want to serve static HTML, Nginx does it all by itself!
  web-app:
    image: bibekiam/devops-dashboard:v2.1
    container_name: compose-custom-app
    restart: always
    environment:
      - REDIS_HOST=data-store
      - REDIS_PORT=6379
    depends_on:
      data-store:
        condition: service_healthy

  data-store:
    image: redis:alpine
    container_name: compose-db-app
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  redis_data: