server {
    listen 80;
    server_name localhost;

    location / {
        # This tells Nginx exactly where to find your index.html file
        root /usr/share/nginx/html;
        index index.html;
    }
}